"use strict";this.default_IdentityRotateCookiesHttp=this.default_IdentityRotateCookiesHttp||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([0x600, ]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){n.setTimeout(function(){throw a;},0)},ba=function(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b},p=function(a){a=Error(a);ba(a,"warning");return a},da=function(a,b){if(a!=null){var c;var e=(c=ca)!=null?c:ca={};c=e[a]||0;c>=b||(e[a]=c+1,a=Error(),ba(a,"incident"),aa(a))}},r=function(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):
a!=null?Symbol(a):Symbol():b},x=function(a,b){u||w in a||ea(a,fa);a[w]=b},ha=function(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)&&a.constructor===Object},y=function(){return typeof BigInt==="function"},z=function(a){a.J=!0;return a},B=function(a){var b=a;if(ia(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(ja(b)&&!Number.isSafeInteger(b))throw Error(String(b));return A?BigInt(a):a=ka(a)?a?"1":"0":ia(a)?a.trim()||"0":String(a)},la=function(a,b){if(a.length>
b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var e=a[c],g=b[c];if(e>g)return!1;if(e<g)return!0}},ma=function(a){var b=a>>>0;C=b;D=(a-b)/4294967296>>>0},G=function(a){if(a<0){ma(-a);var b=E(F(C,D));a=b.next().value;b=b.next().value;C=a>>>0;D=b>>>0}else ma(a)},H=function(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else y()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,
b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+na(c)+na(a));return c},na=function(a){a=String(a);return"0000000".slice(a.length)+a},oa=function(){var a=C,b=D;b&2147483648?y()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=E(F(a,b)),a=b.next().value,b=b.next().value,a="-"+H(a,b)):a=H(a,b);return a},F=function(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]},ra=function(a){switch(typeof a){case "bigint":return!0;case "number":return pa(a);case "string":return qa.test(a);default:return!1}},
xa=function(a){var b=0;b=b===void 0?0:b;if(!ra(a))throw p("int64");var c=typeof a;switch(b){case 2048:switch(c){case "string":return sa(a);case "bigint":return String(I(64,a));default:return ta(a)}case 4096:switch(c){case "string":return ua(a);case "bigint":return B(I(64,a));default:return va(a)}case 0:switch(c){case "string":return sa(a);case "bigint":return B(I(64,a));default:return wa(a)}default:throw Error("Unknown format requested type for int64");}},ya=function(a){var b=a.length;return a[0]===
"-"?b<20?!0:b===20&&Number(a.substring(0,7))>-922337:b<19?!0:b===19&&Number(a.substring(0,6))<922337},za=function(a){if(ya(a))return a;if(a.length<16)G(Number(a));else if(y())a=BigInt(a),C=Number(a&BigInt(4294967295))>>>0,D=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");D=C=0;for(var c=a.length,e=b,g=(c-b)%6+b;g<=c;e=g,g+=6)e=Number(a.slice(e,g)),D*=1E6,C=C*1E6+e,C>=4294967296&&(D+=Math.trunc(C/4294967296),D>>>=0,C>>>=0);b&&(b=E(F(C,D)),a=b.next().value,b=b.next().value,C=a,D=b)}return oa()},
wa=function(a){a=J(a);if(!K(a)){G(a);var b=C,c=D;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);var e=c*4294967296+(b>>>0);b=Number.isSafeInteger(e)?e:H(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a},ta=function(a){a=J(a);if(K(a))a=String(a);else{var b=String(a);ya(b)?a=b:(G(a),a=oa())}return a},sa=function(a){var b=J(Number(a));if(K(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return za(a)},ua=function(a){var b=J(Number(a));if(K(b))return B(b);b=a.indexOf(".");
b!==-1&&(a=a.substring(0,b));return y()?B(I(64,BigInt(a))):B(za(a))},va=function(a){return K(a)?B(wa(a)):B(ta(a))},Aa=function(a){return a},Da=function(a,b,c){var e=Ba;c=c?!!(b&32):void 0;var g=[],k=a.length,d=!1;if(b&64){if(b&256){k--;var f=a[k];var h=k}else h=4294967295,f=void 0;if(!(b&512)){d=!0;var l;var m=((l=Ca)!=null?l:Aa)(f?h- -1:b>>15&1023||536870912,-1,a,f);h=m+-1}}else h=4294967295,b&1||(f=k&&a[k-1],ha(f)?(k--,h=k,m=0):f=void 0);b=void 0;for(l=0;l<k;l++){var v=a[l];if(v!=null&&(v=e(v,c))!=
null)if(l>=h){var q=void 0;((q=b)!=null?q:b={})[l- -1]=v}else g[l]=v}if(f)for(var t in f)a=f[t],a!=null&&(a=e(a,c))!=null&&(k=+t,k<m?g[k+-1]=a:(k=void 0,((k=b)!=null?k:b={})[t]=a));b&&(d?g.push(b):g[h]=b);return g},Ba=function(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Ea(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[w]|0;return a.length===0&&b&1?void 0:Da(a,b,!1)}b=a[L];var c=b===Fa;Ga&&b&&!c&&da(Ha,3);if(c)return M(a);
return}return a},M=function(a){a=a.m;return Da(a,a[w]|0)},N=function(a,b,c){if(a==null){var e=96;c?(a=[c],e|=512):a=[];b&&(e=e&-33521665|(b&1023)<<15)}else{if(!Array.isArray(a))throw Error("i");e=a[w]|0;8192&e||!(64&e)||2&e||Ia();if(e&1024)throw Error("k");if(e&64)return e&16384||x(a,e|16384),a;e|=64;if(c&&(e|=512,c!==a[0]))throw Error("l");a:{c=a;var g=c.length;if(g){var k=g-1,d=c[k];if(ha(d)){e|=256;b=e&512?0:-1;k-=b;if(k>=1024)throw Error("n");for(var f in d)g=+f,g<k&&(c[g+b]=d[f],delete d[f]);
e=e&-33521665|(k&1023)<<15;break a}}if(b){f=Math.max(b,g-(e&512?0:-1));if(f>1024)throw Error("o");e=e&-33521665|(f&1023)<<15}}}x(a,e|16384);return a},Ia=function(){da(Ja,5)},Ka=function(a){return Ea(a)?Number(a):String(a)},La=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},Ma=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},Na=function(a){a=["object"==
typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},O=Na(this),P=function(a,b){if(b)a:{var c=O;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&Ma(c,a,{configurable:!0,writable:!0,value:b})}},Oa=typeof Object.create=="function"?Object.create:function(a){var b=function(){};
b.prototype=a;return new b},Q;if(typeof Object.setPrototypeOf=="function")Q=Object.setPrototypeOf;else{var R;a:{var Pa={a:!0},Qa={};try{Qa.__proto__=Pa;R=Qa.a;break a}catch(a){}R=!1}Q=R?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("b`"+a);return a}:null}
var Ra=Q,Sa=function(a,b){a.prototype=Oa(b.prototype);a.prototype.constructor=a;if(Ra)Ra(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.L=b.prototype},E=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:La(a)};throw Error("c`"+String(a));};
P("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.h=function(d){if(this.g==null){this.g=[];var f=this;this.i(function(){f.l()})}this.g.push(d)};var e=O.setTimeout;b.prototype.i=function(d){e(d,0)};b.prototype.l=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(l){this.j(l)}}}this.g=null};b.prototype.j=function(d){this.i(function(){throw d;
})};var g=function(d){this.h=0;this.i=void 0;this.g=[];this.u=!1;var f=this.j();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.j=function(){function d(l){return function(m){h||(h=!0,l.call(f,m))}}var f=this,h=!1;return{resolve:d(this.B),reject:d(this.l)}};g.prototype.B=function(d){if(d===this)this.l(new TypeError("d"));else if(d instanceof g)this.D(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=!1}f?this.A(d):this.s(d)}};g.prototype.A=
function(d){var f=void 0;try{f=d.then}catch(h){this.l(h);return}typeof f=="function"?this.F(f,d):this.s(d)};g.prototype.l=function(d){this.v(2,d)};g.prototype.s=function(d){this.v(1,d)};g.prototype.v=function(d,f){if(this.h!=0)throw Error("e`"+d+"`"+f+"`"+this.h);this.h=d;this.i=f;this.h===2&&this.C();this.H()};g.prototype.C=function(){var d=this;e(function(){if(d.I()){var f=O.console;typeof f!=="undefined"&&f.error(d.i)}},1)};g.prototype.I=function(){if(this.u)return!1;var d=O.CustomEvent,f=O.Event,
h=O.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=O.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.i;return h(d)};g.prototype.H=function(){if(this.g!=null){for(var d=0;d<this.g.length;++d)k.h(this.g[d]);this.g=null}};var k=new b;g.prototype.D=function(d){var f=this.j();d.o(f.resolve,f.reject)};
g.prototype.F=function(d,f){var h=this.j();try{d.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};g.prototype.then=function(d,f){function h(q,t){return typeof q=="function"?function(W){try{l(q(W))}catch(X){m(X)}}:t}var l,m,v=new g(function(q,t){l=q;m=t});this.o(h(d,l),h(f,m));return v};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.o=function(d,f){function h(){switch(l.h){case 1:d(l.i);break;case 2:f(l.i);break;default:throw Error("f`"+l.h);}}var l=this;this.g==null?k.h(h):
this.g.push(h);this.u=!0};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var l=E(d),m=l.next();!m.done;m=l.next())c(m.value).o(f,h)})};g.all=function(d){var f=E(d),h=f.next();return h.done?c([]):new g(function(l,m){function v(W){return function(X){q[W]=X;t--;t==0&&l(q)}}var q=[],t=0;do q.push(void 0),t++,c(h.value).o(v(q.length-1),m),h=f.next();while(!h.done)})};return g});
P("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});P("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});P("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});P("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});P("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
P("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});P("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});var n=this||self;var ca=void 0;var u=typeof Symbol==="function"&&typeof Symbol()==="symbol",Ta=r("jas",void 0,!0),Ja=r(void 0,"0actk"),L=r("m_m","K",!0),Ha=r(void 0,"mrtk");var fa={G:{value:0,configurable:!0,writable:!0,enumerable:!1}},ea=Object.defineProperties,w=u?Ta:"G";var Ga=typeof L==="symbol",Fa={},Ua={};var ja=z(function(a){return typeof a==="number"}),ia=z(function(a){return typeof a==="string"}),ka=z(function(a){return typeof a==="boolean"});var A=typeof n.BigInt==="function"&&typeof n.BigInt(0)==="bigint";var Ea=z(function(a){return A?a>=Va&&a<=Wa:a[0]==="-"?la(a,Xa):la(a,Ya)}),Xa=Number.MIN_SAFE_INTEGER.toString(),Va=A?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ya=Number.MAX_SAFE_INTEGER.toString(),Wa=A?BigInt(Number.MAX_SAFE_INTEGER):void 0;var C=0,D=0;var I=typeof BigInt==="function"?BigInt.asIntN:void 0,K=Number.isSafeInteger,pa=Number.isFinite,J=Math.trunc,qa=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;var Ca;var Za=B(0),$a=function(a,b,c){var e=a.m,g=e[w]|0;if(g&2)throw Error();var k=b+-1,d=e.length-1,f;k>=d&&((f=g)!=null?f:g=e[w]|0)&256?e[d][b]=c:k<=d?e[k]=c:c!==void 0&&(f=g>>15&1023||536870912,b>=f?c!=null&&(k={},e[f+-1]=(k[b]=c,k),x(e,g|256)):e[k]=c);return a},ab=function(a){var b=void 0;b=b===void 0?Za:b;a=a.m;var c=1+(Ua?0:-1),e=a.length-1;c>=e&&(a[w]|0)&256?a=a[e][1]:c<=e?a=a[c]:a=void 0;c=typeof a;a=a==null?a:c==="bigint"?B(I(64,a)):ra(a)?c==="string"?ua(a):va(a):void 0;return a!=null?a:b},S=function(a,
b,c){if(c!=null){if(typeof c!=="number")throw p("int32");if(!pa(c))throw p("int32");c|=0}$a(a,b,c)};var T=function(a,b,c){this.m=N(a,b,c)};T.prototype.toJSON=function(){return M(this)};T.prototype[L]=Fa;T.prototype.toString=function(){return this.m.toString()};var bb=function(a){this.m=N(a)};Sa(bb,T);var cb=function(a){this.m=N(a,0,"identity.hfcr")};Sa(cb,T);var db=function(a){return function(b){if(b==null||b=="")b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("p");u||w in b||ea(b,fa);b[w]|=32;b=new a(b)}return b}}(cb);var eb=function(a,b,c,e,g){this.l=a;this.i=b;this.j=c;this.h=e;this.g=g};eb.prototype.start=function(){var a=this;if(typeof fetch!=="undefined")if(fb()){var b=U(),c=Date.now();b&&b>c+this.g*1E3&&(b=Date.now()+this.g*1E3,V(b));var e=function(){gb(a).then(function(){setTimeout(e,a.g*1E3)})};setTimeout(function(){e()},b&&b>c?b-c:0)}else hb(this)};
var hb=function(a){ib(a).then(function(){var b=function(){ib(a).then(function(){setTimeout(b,a.g*1E3)})};setTimeout(function(){b()},a.g*1E3)})},ib=function(a){var b=jb(a);return kb(b).then(function(c){c=lb(Ka(ab(c)));c!==a.g&&(a.g=c)}).catch(function(){a.g*=2})},gb=function(a){var b=U();if(!b||Date.now()>=b){var c=Math.floor(Math.random()*1E3);return new Promise(function(e){setTimeout(function(){var g=U();!g||Date.now()>=g?e(mb(a)):e()},c)})}return Promise.resolve()},kb=function(a){a={method:"POST",
credentials:"same-origin",cache:"no-store",mode:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(M(a))};if(typeof AbortController!=="undefined"){var b=new AbortController;setTimeout(function(){b.abort()},3E4);a.signal=b.signal}return fetch(new Request("/RotateCookies",a)).then(function(c){return c.text()}).then(function(c){return db(JSON.stringify(JSON.parse(c.substring(5))[0]))})},jb=function(a){var b=new bb;var c=a.l;c=c==null?c:xa(c);b=$a(b,2,c);a.i!==0&&S(b,1,a.i);
a.j!==0&&S(b,3,a.j);a.h!==0&&S(b,4,a.h);return b},mb=function(a){V(Date.now()+a.g*1E3);var b=jb(a);return kb(b).then(function(c){c=lb(Ka(ab(c)));c!==a.g&&(V(Date.now()+c*1E3),a.g=c)}).catch(function(){a.g*=2;V(Date.now()+a.g*1E3)})},fb=function(){try{var a=window.localStorage;if(!a)return!1;a.setItem("cookieRotationStorageAccessTest","1");a.removeItem("cookieRotationStorageAccessTest");return!0}catch(b){return!1}},lb=function(a){a<60&&(a=60);return a},U=function(){try{var a=window.localStorage.getItem("nextRotationAttemptTs");
if(!a)return null;var b=Math.floor(Number(a));return Number.isNaN(b)?null:b}catch(c){return null}},V=function(a){try{window.localStorage.setItem("nextRotationAttemptTs",a.toString())}catch(b){}};for(var nb=function(a,b,c,e,g){(new eb(a,b,c,e,g)).start()},ob=["init"],Y=n,Z;ob.length&&(Z=ob.shift());)ob.length||nb===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=nb;
}catch(e){_._DumpException(e)}
}).call(this,this.default_IdentityRotateCookiesHttp);
// Google Inc.
